web/router.ex
defmodule Callforpapers.Router do
  use Callforpapers.Web, :router

  import Callforpapers.Auth, only: [authenticate_user: 2, authenticate_organizer: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Callforpapers.Auth, repo: Callforpapers.Repo
  end

  pipeline :registered_users do
    plug :authenticate_user
  end

  pipeline :organizers do
    plug :authenticate_organizer
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Callforpapers do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :delete, :create]
  end

  scope "/", Callforpapers do
    pipe_through [:browser, :registered_users]

    resources "/users", UserController, only: [:show, :index, :edit, :delete, :update]
    resources "/talks", TalkController
    resources "/submissions", SubmissionController
    resources "/callforpapers", CallforpapersController, only: [:show, :index]
    resources "/conferences", ConferenceController, only: [:show, :index]
  end

  scope "/", Callforpapers do
    pipe_through [:browser, :organizers]

    resources "/submissions", SubmissionController, only: [:accept, :reject] do
      post "/acceptance", SubmissionController, :accept, as: :accept
      post "/rejection", SubmissionController, :reject, as: :reject
    end
  end

  scope "/organization/", Callforpapers do
    pipe_through [:browser, :registered_users, :organizers] # Use the default browser stack

    resources "/conferences", ConferenceController
    resources "/callforpapers", CallforpapersController, only: [:edit, :delete, :update, :create, :new] do
      put "/open", CallforpapersController, :open, as: :open
      put "/close", CallforpapersController, :close, as: :close
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Callforpapers do
  #   pipe_through :api
  # end
end

lib/callforpapers/endpoint.ex
defmodule Callforpapers.Endpoint do
  use Phoenix.Endpoint, otp_app: :callforpapers

  socket "/socket", Callforpapers.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :callforpapers, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_callforpapers_key",
    signing_salt: "9nXeYQ2L"

  plug Callforpapers.Router
end

lib/callforpapers/repo.ex
defmodule Callforpapers.Repo do
  use Ecto.Repo, otp_app: :callforpapers
end

web/models/callforpapers.ex
defmodule Callforpapers.Cfp do
  use Callforpapers.Web, :model

  @valid_stati ~w(open closed)

  schema "callforpapers" do
    field :start, Ecto.Date
    field :end, Ecto.Date
    field :status, :string

    belongs_to :conference, Callforpapers.Conference

    timestamps()
  end

  def only_open(query) do
    from s in query, where: s.status == "open"
  end

  def with_conference(query) do
    from s in query, preload: [:conference]
  end

  def valid_state?(status) do
    status in @valid_stati
  end

  def valid_stati, do: @valid_stati

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:start, :end, :status])
    |> validate_required([:start, :end, :status])
    |> Validators.validate_enum(:status, @valid_stati)
    |> assoc_constraint(:conference)
  end
end

web/controllers/callforpapers_controller.ex
defmodule Callforpapers.CallforpapersController do
  use Callforpapers.Web, :controller

  alias Ecto.Changeset
  alias Callforpapers.Cfp
  alias Callforpapers.Conference
  alias Callforpapers.Submission

  plug :load_conferences when action in [:create, :update, :new, :edit]

  def load_conferences(conn, _params) do
    conferences = Conference
           |> Conference.titles_and_ids
           |> Conference.filter_on_organizer(conn.assigns.current_user)
           |> Repo.all

    conn
    |> assign(:conferences, conferences)
  end

  def index(conn, _params) do
    callforpapers = Cfp |> Cfp.with_conference |> Repo.all
    render(conn, "index.html", callforpapers: callforpapers)
  end

  def new(conn, _params) do
    changeset =
        %Conference{}
        |> build_assoc(:callforpapers)
        |> Cfp.changeset(%{status: "open"})

    render(conn, "new.html", changeset: changeset, cfp_stati: Cfp.valid_stati)
  end

  def create(conn, %{"cfp" => callforpapers_params}) do
    changeset =
        Repo.get(Conference, callforpapers_params["conference_id"])
        |> build_assoc(:callforpapers)
        |> Cfp.changeset(callforpapers_params)

    case Repo.insert(changeset) do
      {:ok, _callforpapers} ->
        conn
        |> put_flash(:info, "Callforpapers created successfully.")
        |> redirect(to: callforpapers_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, cfp_stati: Cfp.valid_stati)
    end
  end

  def show(conn, %{"id" => id}) do
    callforpapers = Repo.get!(Cfp |> Cfp.with_conference, id)

    submissions =
      (from f in Submission, where: f.cfp_id == ^id, preload: [{:talk, :user}])
      |> Repo.all
      |> Enum.sort(fn a, b -> Submission.title(a) < Submission.title(b) end)

    render(conn, "show.html", cfp: callforpapers, submissions: submissions)
  end

  defp set_cfp_stat(conn, id, state, info, warn) do
    changeset =
      Cfp
      |> Repo.get!(id)
      |> Cfp.changeset(%{status: state})

    conn =
      case Repo.update(changeset) do
        {:ok, _} ->
          conn
          |> put_flash(:info, info)
        {:error, _} ->
          conn
          |> put_flash(:warn, warn)
      end

    conn
    |> redirect(to: callforpapers_path(conn, :index))
  end

  def open(conn, %{"callforpapers_id" => id}) do
    set_cfp_stat(conn, id, "open", "Callforpapers opened successfully.", "Callforpapers could not be opened.")
  end

  def close(conn, %{"callforpapers_id" => id}) do
    set_cfp_stat(conn, id, "closed", "Callforpapers closed successfully.", "Callforpapers could not be closed.")
  end

  def edit(conn, %{"id" => id}) do
    callforpapers = Repo.get!(Cfp, id)
    changeset = Cfp.changeset(callforpapers)
    render(conn, "edit.html", cfp: callforpapers, changeset: changeset, cfp_stati: Cfp.valid_stati)
  end

  def update(conn, %{"id" => id, "cfp" => callforpapers_params}) do
    callforpapers = Repo.get!(Cfp, id) |> Repo.preload(:conference)
    conf_id = callforpapers_params["conference_id"] || callforpapers.conference_id

    # in german: ekliger Gulasch...das muss doch einfacher gehen
    changeset =
      if conf_id == callforpapers.conference_id do
        Cfp.changeset(callforpapers, callforpapers_params)
      else
        new_conf = Repo.get!(Conference, conf_id)

        %Cfp{id: callforpapers.id}
          |> Changeset.change
          |> Cfp.changeset(callforpapers_params)
          |> Changeset.put_assoc(:conference, new_conf)
      end

    case Repo.update(changeset) do
      {:ok, callforpapers} ->
        conn
        |> put_flash(:info, "Callforpapers updated successfully.")
        |> redirect(to: callforpapers_path(conn, :show, callforpapers))
      {:error, changeset} ->
        render(conn, "edit.html", cfp: callforpapers, changeset: changeset, cfp_stati: Cfp.valid_stati)
    end
  end

  def delete(conn, %{"id" => id}) do
    callforpapers = Repo.get!(Cfp, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(callforpapers)

    conn
    |> put_flash(:info, "Callforpapers deleted successfully.")
    |> redirect(to: callforpapers_path(conn, :index))
  end
end

web/views/callforpapers_view.ex
defmodule Callforpapers.CallforpapersView do
  use Callforpapers.Web, :view
  alias Callforpapers.Submission
  alias Callforpapers.User
end

web/templates/callforpapers/edit.html.eex
<h2>Edit callforpapers</h2>

<%= render "form.html", changeset: @changeset,
                        conn: @conn,
                        cfp_stati: @cfp_stati,
                        conferences: @conferences,
                        mode: :edit,
                        action: callforpapers_path(@conn, :update, @cfp) %>

web/templates/callforpapers/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :start, class: "control-label" %>
    <%= date_select f, :start, class: "form-control" %>
    <%= error_tag f, :start %>
  </div>

  <div class="form-group">
    <%= label f, :end, class: "control-label" %>
    <%= date_select f, :end, class: "form-control" %>
    <%= error_tag f, :end %>
  </div>

  <%= if @mode == :new do %>
    <div class="form-group">
      <%= label f, :conference_id, class: "control-label" %>
      <%= select f, :conference_id, @conferences, class: "form-control", prompt: "--- Please select ---" %>

      <%= error_tag f, :conference_id %>
    </div>
  <% end %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
    <%= link "Back", to: callforpapers_path(@conn, :index), class: "btn btn-secondary" %>
  </div>
<% end %>

web/templates/callforpapers/index.html.eex
<h2>Listing callforpapers</h2>

<table class="table">
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Status</th>
      <th>Conference</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for callforpapers <- @callforpapers do %>
    <tr>
      <td><%= callforpapers.start %></td>
      <td><%= callforpapers.end %></td>
      <td>
          <%= if callforpapers.status == "open" do %>
            <%= fa_icon("unlock") %>
          <% else %>
            <%= fa_icon("lock") %>
          <% end %>
      </td>
      <td><%= callforpapers.conference.title %></td>

      <td class="text-right">
        <%= if Callforpapers.User.is_organizer?(@current_user) do %>
          <%= if callforpapers.status == "open" do %>
            <%= link fw_icon("lock"), title: "Close", method: :put, to: callforpapers_close_path(@conn, :close, callforpapers) %>
          <% else %>
            <%= link fw_icon("unlock"), method: :put, title: "Open", to: callforpapers_open_path(@conn, :open, callforpapers) %>
          <% end %>
        <% end %>

        <%= link fw_icon("eye"), title: "Show", to: callforpapers_path(@conn, :show, callforpapers) %>
        <%= if Callforpapers.User.is_organizer?(@current_user) do %>
          <%= link fw_icon("pencil"), title: "Edit", to: callforpapers_path(@conn, :edit, callforpapers) %>
          <%= link fw_icon("trash"), title: "Delete", to: callforpapers_path(@conn, :delete, callforpapers), method: :delete, data: [confirm: "Are you sure? All submissions to this cfp will be delted, too."] %>
        <% else %>
          <%= link fw_icon("send"), title: "Submit talk", to: submission_path(@conn, :new) %>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= if Callforpapers.User.is_organizer?(@current_user) do %>
  <%= link fa_icon("plus-square 2x"), title: "New CfP", to: callforpapers_path(@conn, :new) %>
<% end %>

web/templates/callforpapers/new.html.eex
<h2>New callforpapers</h2>

<%= render "form.html", changeset: @changeset,
                        conn: @conn,
                        cfp_stati: @cfp_stati,
                        conferences: @conferences,
                        mode: :new,
                        action: callforpapers_path(@conn, :create) %>

web/templates/callforpapers/show.html.eex
<h2>Show callforpapers</h2>

<ul>

  <li>
    <strong>Conference:</strong>
    <%= @cfp.conference.title %>
  </li>

  <li>
    <strong>Start:</strong>
    <%= @cfp.start %>
  </li>

  <li>
    <strong>End:</strong>
    <%= @cfp.end %>
  </li>

  <li>
    <strong>Status:</strong>
    <%= @cfp.status %>
  </li>

</ul>

<div class="form-group">
  <%= if Callforpapers.User.is_organizer?(@current_user) do %>
    <%= link "Edit", to: callforpapers_path(@conn, :edit, @cfp),  class: "btn btn-small btn-primary" %>
    <%= if @cfp.status == "open" do %>
      <%= link "Close", to: callforpapers_path(@conn, :edit, @cfp),  class: "btn btn-small btn-primary" %>
    <% else %>
      <%= link "Open", to: callforpapers_path(@conn, :edit, @cfp),  class: "btn btn-small btn-primary" %>
    <% end %>
  <% end %>
  <%= link "Back", to: callforpapers_path(@conn, :index), class: "btn btn-small btn-secondary" %>
</div>

<%= if User.is_organizer?(@current_user) do %>
  <h2>Current Submissions</h2>

  <table class="table">
    <thead>
      <tr>
        <th>Submission</th>
        <th>Presenter</th>
        <th>Short summary</th>
        <th>Duration</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
  <%= for submission <- @submissions do %>
      <tr>
        <td><%= Submission.title(submission) %></td>
        <td><%= Submission.presenter(submission) %></td>
        <td><%= submission.talk.duration %></td>
        <td><%= submission.talk.shortsummary %></td>
        <td>
          <%= if submission.status == "accepted" do %>
            <%= fa_icon("check") %>
          <% end %>
          <%= if submission.status == "rejected" do %>
            <%= fa_icon("times") %>
          <% end %>
        </td>
        <td class="text-right">
          <%= if !Submission.accepted?(submission) do %>
            <%= link fw_icon("check"), title: "Accept", to: submission_accept_path(@conn, :accept, submission.id) %>
          <% end %>
          <%= if !Submission.rejected?(submission) do %>
            <%= link fw_icon("times"), title: "Reject", to: submission_reject_path(@conn, :reject, submission.id) %>
          <% end %>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>
<% end %>