web/router.ex
defmodule Callforpapers.Router do
  use Callforpapers.Web, :router

  import Callforpapers.Auth, only: [authenticate_user: 2, authenticate_organizer: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Callforpapers.Auth, repo: Callforpapers.Repo
  end

  pipeline :registered_users do
    plug :authenticate_user
  end

  pipeline :organizers do
    plug :authenticate_organizer
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Callforpapers do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :delete, :create]
  end

  scope "/", Callforpapers do
    pipe_through [:browser, :registered_users]

    resources "/users", UserController, only: [:show, :index, :edit, :delete, :update]
    resources "/talks", TalkController
    resources "/submissions", SubmissionController
    resources "/callforpapers", CallforpapersController, only: [:show, :index]
    resources "/conferences", ConferenceController, only: [:show, :index]
  end

  scope "/", Callforpapers do
    pipe_through [:browser, :organizers]

    resources "/submissions", SubmissionController, only: [:accept, :reject] do
      post "/acceptance", SubmissionController, :accept, as: :accept
      post "/rejection", SubmissionController, :reject, as: :reject
    end
  end

  scope "/organization/", Callforpapers do
    pipe_through [:browser, :registered_users, :organizers] # Use the default browser stack

    resources "/conferences", ConferenceController
    resources "/callforpapers", CallforpapersController, only: [:edit, :delete, :update, :create, :new] do
      put "/open", CallforpapersController, :open, as: :open
      put "/close", CallforpapersController, :close, as: :close
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Callforpapers do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="jumbotron">
  <p class="lead">Simple administration for paper submissions and call-for-papers.</p>
  <%= if !@current_user do %>
    Please login using the <%= link fa_icon("user-circle", text: "Login"), to: session_path(@conn, :new), title: "Login" %> button or register as a presenter using the
    <%= link fa_icon("user-plus", text: "Register"), to: user_path(@conn, :new), title: "Register"%> button.
  <%= else %>
    <div class="menu-container">
    <div class="menu-list">


      <%= if Callforpapers.User.is_organizer?(@current_user) do %>
        <div class="menu-item">
          <%= link fw_icon("users"), to: user_path(@conn, :index), title: "Presenters" %>
          allows managment of all registered users.
        </div>

        <div class="menu-item">
          <%= link fw_icon("graduation-cap"), to: conference_path(@conn, :index), title: "Conferences" %> takes you to the conference administration.
        </div>
      <% end %>

      <div class="menu-item">
        <%= link fw_icon("volume-up"), to: callforpapers_path(@conn, :index), title: "Call-for-Papers" %> takes you to the call-for-papers section.
      </div>

      <%= if Callforpapers.User.is_presenter?(@current_user) do %>
        <div class="menu-item">
          <%= link fw_icon("book"), to: talk_path(@conn, :index), title: "My talks" %> shows you your current presentations.
        </div>

        <div class="menu-item">
          <%= link fw_icon("send"), to: submission_path(@conn, :index), title: "My Submissions" %> takes you to your submissions.
        </div>
      <% end %>

      <div class="menu-item">
        <%= link  fw_icon("power-off"), to: session_path(@conn, :delete, @current_user), method: "delete", title: "Logout" %> logs you off.
      </div>
      <div class="menu-item">
        <%= link fw_icon("home"), to: page_path(@conn, :index), title: "Home" %> takes you to this page.
      </div>
    </div>
    </div>
  <%= end %>
</div>

<div class="row marketing">
  <div class="col-lg-6">
  </div>
</div>